language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install --user -r requirements.txt
  - pip install --user .
# command to run tests
script: functional_tests/tests.py