language: python
python:
  - "2.7"
packages:
  - openjdk-7-jdk
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - python -m unittest wiremockmanager
  - python functional_tests/tests.py